package github

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

const apiBase = "https://api.github.com"

// Client handles communication with the GitHub API.
type Client struct {
	token      string
	httpClient *http.Client
}

// NewClient creates a new GitHub API client.
func NewClient(token string) *Client {
	return &Client{
		token: token,
		httpClient: &http.Client{
			Timeout: 30 * time.Second,
		},
	}
}

// Issue represents a review issue to post as a comment.
type Issue struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	File        string `json:"file"`
	Line        int    `json:"line"`
	Severity    string `json:"severity"`
	Suggestion  string `json:"suggestion"`
}

// PostReviewComment posts a summary comment on a pull request.
func (c *Client) PostReviewComment(owner, repo string, prNumber int, issues []Issue, summary string) error {
	body := buildCommentBody(issues, summary)

	payload := map[string]string{"body": body}
	jsonBody, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("marshaling comment: %w", err)
	}

	url := fmt.Sprintf("%s/repos/%s/%s/issues/%d/comments", apiBase, owner, repo, prNumber)

	req, err := http.NewRequest(http.MethodPost, url, bytes.NewReader(jsonBody))
	if err != nil {
		return fmt.Errorf("creating request: %w", err)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("X-GitHub-Api-Version", "2022-11-28")

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("sending request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusCreated {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitHub API returned status %d: %s", resp.StatusCode, truncate(string(respBody), 300))
	}

	return nil
}

// buildCommentBody formats issues into a markdown comment.
func buildCommentBody(issues []Issue, summary string) string {
	var sb strings.Builder

	sb.WriteString("## 🔍 Larasense Limbo — AI Code Review\n\n")
	sb.WriteString(summary + "\n\n")

	if len(issues) == 0 {
		sb.WriteString("✅ No issues found. Great job!\n")
		return sb.String()
	}

	// Group by file
	grouped := make(map[string][]Issue)
	for _, issue := range issues {
		file := issue.File
		if file == "" {
			file = "(unknown)"
		}
		grouped[file] = append(grouped[file], issue)
	}

	for file, fileIssues := range grouped {
		fmt.Fprintf(&sb, "### 📄 `%s`\n\n", file)

		for _, issue := range fileIssues {
			icon := severityIcon(issue.Severity)
			fmt.Fprintf(&sb, "%s **[%s]** %s", icon, strings.ToUpper(issue.Severity), issue.Title)
			if issue.Line > 0 {
				fmt.Fprintf(&sb, " (line %d)", issue.Line)
			}
			sb.WriteString("\n")
			fmt.Fprintf(&sb, "> %s\n", issue.Description)
			if issue.Suggestion != "" {
				fmt.Fprintf(&sb, "> 💡 **Suggestion:** %s\n", issue.Suggestion)
			}
			sb.WriteString("\n")
		}
	}

	sb.WriteString("---\n")
	sb.WriteString("*Generated by [larasense-limbo](https://github.com/Mattel-Limbo/larasense-limbo)*\n")

	return sb.String()
}

func severityIcon(severity string) string {
	switch strings.ToLower(severity) {
	case "high":
		return "🔴"
	case "medium":
		return "🟡"
	case "low":
		return "🔵"
	default:
		return "⚪"
	}
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}
