version: 2

project_name: larasense-limbo

builds:
  - main: .
    binary: larasense-limbo
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/Mattel-Limbo/larasense-limbo/cmd.Version={{.Version}}
      - -X github.com/Mattel-Limbo/larasense-limbo/cmd.Commit={{.ShortCommit}}
      - -X github.com/Mattel-Limbo/larasense-limbo/cmd.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
